In [18]:
import numpy as np
import time

In [21]:
'''
Try to make matrix:
1 1 1 1 1
1 0 0 0 1
1 0 9 0 1
1 0 0 0 1
1 1 1 1 1
'''

# My code
matrix = np.ones((5,5))
for row in range(matrix.shape[0]):
    if row in (0, 4):
        continue
    for col in range(matrix.shape[1]):
        if col in (0,4):
            continue
        elif (row, col) == (2, 2):
            matrix[row, col] = 9
        else:
            matrix[row, col] = 0
print(matrix)

# His code
print("")
ones = np.ones((5,5))
zeros = np.zeros((3,3))
zeros[1, 1] = 9
ones[1:4, 1:4] = zeros
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [41]:
'''

1  2  3  4  5
6  7  8  9  10
11 12 13 14 15
16 17 18 19 20 
21 22 23 24 25
26 27 28 29 30

'''

# Set up
a = np.zeros((6, 5))
for row in range(a.shape[0]):
    for col in range(a.shape[1]):
        a[row, col] = 1 + col + 5 * row
        
'''

11 12 
16 17

'''
a[2:4, 0:2]


'''
2
    8
        14
            20
'''

a[[0,1,2,3], [1,2,3,4]]

'''
4  5


24 25
29 30
'''

a[[0,4,5], 3:]

array([[ 4.,  5.],
       [24., 25.],
       [29., 30.]])